.PHONY: clean All Project_Title Project_Build

All: Project_Title Project_Build

Project_Title:
	@echo "----------Building project:[ top_test - BuildSet ]----------"

Project_Build:
	@make -r -f top_test.mk -j 8 -C  ./ 


clean:
	@echo "----------Cleaning project:[ top_test - BuildSet ]----------"

