#ifndef __BOOT_TEST_CONFIG_H__
#define __BOOT_TEST_CONFIG_H__
#define CONFIG_ARCH_RV32 1
#define CONFIG_CPU_E902 1
#define CONFIG_ROM
//#define CONFIG_BSS_INIT
#define CONFIG_HAVE_VIC 1
#define CONFIG_ARCH_INTERRUPTSTACK 384
#define CONFIG_ARCH_TRAPSTACK 128
#define CONFIG_TICK_HZ	100
#endif
