.PHONY: clean All Project_Title Project_Build

All: Project_Title Project_Build

Project_Title:
	@echo "----------Building project:[ i2c_master_self_loop_slave - BuildSet ]----------"

Project_Build:
	@make -r -f i2c_master_self_loop_slave.mk -j 8 -C  ./ 


clean:
	@echo "----------Cleaning project:[ i2c_master_self_loop_slave - BuildSet ]----------"

