.PHONY: clean All Project_Title Project_Build

All: Project_Title Project_Build

Project_Title:
	@echo "----------Building project:[ uart1_rx - BuildSet ]----------"

Project_Build:
	@make -r -f uart1_rx.mk -j 8 -C  ./ 


clean:
	@echo "----------Cleaning project:[ uart1_rx - BuildSet ]----------"

