#ifndef __UART_TEST_CONFIG_H__
#define __UART_TEST_CONFIG_H__
#define CONFIG_ARCH_RV32 1
#define CONFIG_CPU_E902 1
#define CONFIG_KERNEL_NONE 1
#define CONFIG_HAVE_VIC 0
#define CONFIG_HAVE_VECTORS 0
#define CONFIG_ARCH_INTERRUPTSTACK 384
#define CONFIG_ARCH_TRAPSTACK 128
#define CONFIG_BSS_INIT 0
#endif
