.PHONY: clean All Project_Title Project_Build

All: Project_Title Project_Build

Project_Title:
	@echo "----------Building project:[ test1 - BuildSet ]----------"

Project_Build:
	@make -r -f test1.mk -j 8 -C  ./ 


clean:
	@echo "----------Cleaning project:[ test1 - BuildSet ]----------"

