.PHONY: clean All Project_Title Project_Build

All: Project_Title Project_Build

Project_Title:
	@echo "----------Building project:[ uart2_tx - BuildSet ]----------"

Project_Build:
	@make -r -f uart2_tx.mk -j 8 -C  ./ 


clean:
	@echo "----------Cleaning project:[ uart2_tx - BuildSet ]----------"

