#ifndef __BOOT_TEST_CONFIG_H__
#define __BOOT_TEST_CONFIG_H__
#define CONFIG_ARCH_RV32 1
#define CONFIG_CPU_E902 1
#define CONFIG_HAVE_VIC 0
#define __NO_BOARD_INIT
#define CONFIG_ARCH_INTERRUPTSTACK 192
#define CONFIG_CONSOLE_HANDLE	1
#endif
