.PHONY: clean All Project_Title Project_Build

All: Project_Title Project_Build

Project_Title:
	@echo "----------Building project:[ mem_test - BuildSet ]----------"

Project_Build:
	@make -r -f mem_test.mk -j 12 -C  mem_test 


clean:
	@echo "----------Cleaning project:[ mem_test - BuildSet ]----------"

