#ifndef __CONFIG_H__
#define __CONFIG_H__
#define CONFIG_ARCH_RV32 1
#define CONFIG_CPU_E902 1
#define CONFIG_ROM
#define CONFIG_BSS_INIT
#define CONFIG_HAVE_VIC 1
#define CONFIG_ARCH_INTERRUPTSTACK 384
#define CONFIG_ARCH_TRAPSTACK 128
#define CONFIG_WDT
#define CONFIG_TIMER
#define CONFIG_TICK_US
#define CONFIG_CONSOLE_HANDLE	1
#define CONFIG_CONSOLE_RXSIZE	64
#define CONFIG_CONSOLE_TXSIZE	32
#define CONFIG_PRINTF
#define CONFIG_SHELL
#ifdef CONFIG_SHELL
 #define CONFIG_CMD_READ
 #define CONFIG_CMD_WRITE
 #define CONFIG_CMD_SLEEP
#endif
#endif
