.PHONY: clean All Project_Title Project_Build

All: Project_Title Project_Build

Project_Title:
	@echo "----------Building project:[ uart_test - BuildSet ]----------"

Project_Build:
	@make -r -f uart_test.mk -j 12 -C  uart_test 


clean:
	@echo "----------Cleaning project:[ uart_test - BuildSet ]----------"

